### ISSUE TITLE
Transport reactions not loading correctly in 3D

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#762] opened 2021-11-11 08:17 UTC
**Describe the bug**
Transport reactions in 3D is not correctly

**To reproduce**
Visit https://metabolicatlas.org/explore/Human-GEM/map-viewer/transport_reactions?dim=3d

**Expected behavior**
That users are able to view the transport reactions network.
Note that when trying out the fix, make sure that it is also functional with search values, e.g https://metabolicatlas.org/explore/Human-GEM/map-viewer/transport_reactions?dim=3d&panel=0&sel=MAR05094&search=MAR05094&coords=-4046.68,-23369.77,0.15,0,0,500&g1=None&g2=None

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/b7d9063c-56bc-4080-8680-bdb348562505)

**others**

The server might not be functioning as normal after seeing this error. It will be back to normal after a while (ca 10 min)

**Comment by mihai-sysbio** [comment] 2021-11-11 08:32
More info: not a problem locally (for me)

![image](https://user-images.githubusercontent.com/23480589/141264549-31360fb9-cf4f-438a-be7b-f1ef15cbe727.png)

**Comment by inghylt** [comment] 2021-11-11 08:37
Not a problem locally for me either

**Comment by e0** [comment] 2021-11-15 12:53
Related to the server hanging problem. I feel like this is a good example that shows we should **not** upgrade dependencies unless it's absolutely critical. At least until we have automated testing. Any time we upgrade any dependencies there is risk for something like this happening.

**Comment by e0** [comment] 2021-11-15 18:25
Looking into this problem now.

First off all, it looks like the apoc plugin that matches `4.2.5` is no longer available from https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json Changing the docker image version to `4.2.11` in the `Dockerfile` works.

With that out of the way, it is actually quite easy to consistently trigger the problem that locks up the DB. For example, visit `/explore/Human-GEM/map-viewer/transport_reactions?dim=3d`, in a second tab wait 10-15 seconds and visit `/explore/Human-GEM/gem-browser`. It now takes 2.4 min to load the `/api/v2/repository/integrated_models/` response. For comparison the `/api/v2/3d-network?model=HumanGem&version=1_10_0&type=subsystem&id=transport_reactions` took 2.8 min to load in the first tab.

Note that if you visit `/explore/Human-GEM/gem-browser` within the first 10-15 seconds the page loads in a normal time so it takes a bit of time for the server to lock up.

This is quite concerning since it means that anytime one of these pages that involves a long request is triggered, there is risk of the DB locking up for everyone.

Just wanted to report the findings so far. Continuing with looking for a solution now.

**Comment by mihai-sysbio** [comment] 2021-11-15 19:52
Wow this is totally unexpected from Express - `/api/v2/repository/integrated_models/` is a simple request, to be resolved by serving a json file. Is there a way to confirm which container is locking up?

**Comment by e0** [comment] 2021-11-15 20:43
> Wow this is totally unexpected from Express - `/api/v2/repository/integrated_models/` is a simple request, to be resolved by serving a json file. Is there a way to confirm which container is locking up?

The short answer is that it is the `api` container that is locked up and it's caused by the 3d map layout generation. There is more details provided in #776.

**Closed** 2021-11-16 12:38 UTC
Labels: bug, critical

**Comment by e0** [comment] 2021-11-16 12:40
After working on it, I think I would mark this as a 3. Please note that since this is a quite urgent fix, some details are left for another issue that was [mentioned here](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/776#issuecomment-970053675).
