### ISSUE TITLE
Improve handling of timeline svg

### ISSUE THREAD

**Issue by MalinAhlberg** [MetabolicAtlas/MetabolicAtlas#1091] opened 2022-08-15 06:33 UTC
**Please describe the feature**

As a developer, I want all files to behave well with respect to the version control so that I don't have to be confused or  spend time fixing it.

The file `frontend/src/assets/gemRepository/integratedModelsTimeline.svg` sometimes appears as manually updated when you move between branches and has to be restored/deleted/added.

**Acceptance Criteria**

- [ ] move the `integratedModelsTimeline.svg` out of the current repository
- [ ] create a new issue for creating the procedure to manage this file in the `data-files` repository

**Additional context**

**Comment by e0** [comment] 2022-09-09 13:18
We discussed about handling task disagreement a bit during the retrospective today. There were some good discussion and suggestion of handling things in writing and presenting different alternatives.

For this case, I think there is still disagreement on the second acceptance criteria. I think the disagreement is on whether this file should be tracked in `data-files` or not. Following are the two alternatives as well as my motivation. If anyone disagrees or has any other suggestions please add a comment!

1. Add a procedure about how to manage the GEMS timeline SVG file in `data-files`.
2. Do not include the GEMS timeline SVG file in any repos.

I'm in favor of option 2 because of the following reasons.

- I don't see how this file, especially older versions of it, would be useful for users outside the website.
- The file is enhanced with colors and interactivity by the website. The raw image itself looks different (see below).

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/423498/189358138-ad9d89cc-3713-4da7-a32a-d7b11c650f7c.png">

**Comment by inghylt** [comment] 2022-09-12 11:22
I'm also for 2. I have a hard time imagining a reason why users would like to be able to obtain a previous version of this particular image.

**Comment by MalinAhlberg** [comment] 2022-09-12 12:06
I agree that 2 seems like a reasonable and easy way forward, but I'm also curious if @mihai-sysbio did have any specific use cases in mind for keeping versions of the timeline SVG?

**Comment by nanjiangshu** [comment] 2022-09-12 15:15
I'm also for 2, since firstly the SVG image itself seems not very useful as Shan showed; and secondly, the older version of the map is contained in the newer version of map.

**Comment by mihai-sysbio** [comment] 2022-09-14 18:09
In an academic environment, working reproducibly is a _must_, especially when building a reputable data resource. While one can claim that an image is reproducible because the code to create it is open-source, very quickly it gets very hard to reproduce an old image. One has to be familiar with and have the software installed, and select the right version of the input file.

For robustness, we already copy versioned and Zenodo-archived GEMs into our _data-files_ repository. In a way, the image itself is a data file like our SVG maps. Having this SVG file also versioned is in line with the current approach of versioning our inputs in addition to our code. Even if this data file is created programatically by us, it doesn't make the image more easy to cite or reference reliably.

And here is a concrete, yet imaginary, use-case:

A user comes arrives on the website, goes to the GEM repository and thinks the image is really relevant for their work so they save a copy. They might even include the figure in a presentation or publication. After some months, they have another look at the website and see a different image: different styling, some new versions of GEMs, and arrows have changed place (bugs).
Sure, the content of the old map is embedded in the new, with better styling and with fewer bugs. But now the initial figure they saved a copy of appears fictional, i.e. as if it hadn't existed before.

I shouldn't need to say we _have to_ version this file in my capacity as a PM - if I do, it means I haven't communicated the need well enough.

**Comment by e0** [comment] 2022-09-14 22:07
I think the theory for wanting to make things reproducible is fine. In practical terms this sounds really difficult and the website currently does not guarantee that all assets are reproducible.

Some examples are the metabolite images generated using `RDKit` and the Export functionality for Interaction partners. If a user finds a metabolite image based on buggy `smiles` value, uses that in a publication, and if this value is fixed in a later release then it's the same problem as the imaginary use-case. It seems like there are many parts of the website that are not easily reproducible. So in this context it does not make much sense for me to strive for reproducibility of this SVG file, especially when it seems to have less scientific significance than many other parts of the website.

Another problem with this use-case is that when the user comes to the website and saves that version of the image, that is going to be visually different from the `frontend/src/assets/gemRepository/integratedModelsTimeline.svg` one as mentioned above. For example it does not have any indicator of what the current version is for each GEM. I guess I kind of view this SVG file as a stepping stone between raw data and final presentation, not as something that can or should be presented by itself.

With all this said, I'm happy that you are mentioning the PM role in accordance to what we discussed earlier. If we need to go ahead with this, that is fine. It would be helpful though if you could address the last couple of concerns I mentioned.

**Comment by mihai-sysbio** [comment] 2022-10-22 08:30
> the website currently does not guarantee that all assets are reproducible

>  It seems like there are many parts of the website that are not easily reproducible.

The reproducible aspect adds a development cost that cannot be covered every time.

> metabolite images generated using `RDKit`

For the `RDKit` example, the users are much less likely to cite Metabolic Atlas. Instead, it more common to use `RDKit` directly - at least, there is that alternative, and it doesn't take that many lines of code.

> Export functionality for Interaction partners

Here we at least provide a Graphml that can be loaded with other tools to generate (another version of) the image. The reproducibility of the Graphml is still tough nut to crack.

> For example it does not have any indicator of what the current version is for each GEM.

The information required for the current version of each GEM exists in the `data-files` repository, so this highlight could be in fact part of the image generation process.

**Comment by e0** [comment] 2022-10-31 11:41
From what I remember, what we decided in the latest backlog refinement is the following:

1. Stop tracking `frontend/src/assets/gemRepository/integratedModelsTimeline.svg` in this repo.
2. The timeline SVG could be useful in publications, however it's not suitable in its current state (too wide and colors not included). A new issue has been added for this here: #1186

Please let me know if I missed anything.

**Closed** 2022-11-02 08:09 UTC
