### ISSUE TITLE
Fix so clicking search result in quick search does not lead to error message

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#731] opened 2021-10-29 13:22 UTC
**Describe the bug**
Something is not working correctly with the connection between search result in quick search and resulting page in gem browser. Both the screen shots are the result from pressing a match in the quick search.

**To reproduce**
Choose Zebrafish-GEM in the quick search
Search after Poglut in the quick search 
Click the resulting matching gene

If the error is not shown, play around with switching between different GEM:s and redoing the search for Poglut and pressing the top most result

**Expected behavior**
If a match is found in quick search, I expect to be able to click on that match and go to a gem browser page without any errors

**Screenshots**
1. Different GEM in url compared to GEM in error message
![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/007823de-fa16-43d8-b681-bdceb9106b9f)

2. Same GEM in url as error message
![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/fbc49b0f-c1a3-44c2-a6cc-9e7c183b7ac8)

**Comment by nanjiangshu** [comment] 2021-12-07 13:59
Hi @inghylt, @e0 and @MalinAhlberg, I played a bit with the Gem search but could not reproduce this error. I think this bug is most likely already been solved with the issue #734. Since the bug described here looks very similar to https://github.com/MetabolicAtlas/MetabolicAtlas/issues/734#issuecomment-966948198.

**Comment by inghylt** [comment] 2021-12-07 14:09
I'm not able to reproduce it either. Nice that it seems to be fixed already!

**Comment by MalinAhlberg** [comment] 2021-12-07 14:21
Same here, I can't reproduce it either :raised_hands: .

**Comment by e0** [comment] 2021-12-07 18:01
I can't reproduce it either. I vaguely remember us talking about an issue like this that could be related to some cache but not sure if that was actually valid. I did try a bunch of other genes in several different models and didn't notice any problems.

**Comment by nanjiangshu** [comment] 2021-12-08 09:23
Great! Then I will close this issue.

**Closed** 2021-12-08 09:23 UTC
Labels: bug, hotjar
