### ISSUE TITLE
Duplicate enzymes

### ISSUE THREAD

**Issue by perjo** [MetabolicAtlas/MetabolicAtlas#1119] opened 2022-08-25 12:06 UTC
**Describe the bug**
There are a lot of duplicate rows in the enzyme table (coming from the originating text files). 

**Steps to reproduce**

See for exemple: 

![image.png](https://images.zenhubusercontent.com/626697ae6d06b7eb7ed6729d/36025705-7d09-4222-978a-e6dc8fd346d2)

Or run this query

```
select gene, organism, domain, ko, reaction_id, ec_number, compound, kcat_values, count(*) 
from enzymes
group by gene, organism, domain, ko, reaction_id, ec_number, compound, kcat_values 
having count(*) > 1;
```

**Expected behavior**

No duplicates are shown in GUI

**Screenshots**

**Additional context**

**Comment by Yu-sysbio** [comment] 2022-08-26 09:54
The duplicates are caused by the reactions in which a substrate is also a product, please check the KEGG [example](https://www.genome.jp/entry/R02078). We could just make them unique in the next release.

**Comment by mihai-sysbio** [comment] 2022-08-26 09:57
Thanks @Yu-sysbio, making them unique sounds like a good idea.
Based on this explanation, I will close this issue, as it will be resolved on its own in a future deployment.

**Closed by mihai-sysbio** 2022-08-26 09:57 UTC
Labels: bug
