### ISSUE TITLE
research a strategy for the 3D viewer

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#1130] opened 2022-09-12 09:34 UTC
**Please describe the feature**

As a developer, I want to know what is the best strategy to replace the Interaction Partners viewer so that the visualistion is snappy (has good performance) and some of the heavy JS library can be removed.

**Acceptance Criteria**

- [ ] The changes are tested on multiple models and browsers
- [ ] The API response is the same as before
- [ ] The changes do not affect the deployment
- [ ] The changes do not reduce the performance

**Additional context**

For a long time we have had this big feature planned [custom network](https://github.com/MetabolicAtlas/private-issues/issues/66). The refactoring of the IP is seen as a stepping stone so that we can go from the static/fixed network view of the 3D viewer to a more interactive one, while maintaining all the performance aspects. This includes keeping the JS compact, ie by not having different packages for very similar features unless benefits are clear. Moreover, there is refactoring work planned for the 3D viewer so it would be a 2-for-1 to gain the benefits of that future refactoring propagated to different parts of the website.

**Comment by mihai-sysbio** [comment] 2022-09-19 12:49
Adding here a few more details based on follow-up question from @inghylt:
1. In interaction partners, the nodes are only genes and metabolites. As a long-term version, one should design the system with the possibility to also have just genes or just metabolites. This is, however, beyond the scope here.
2. The reaction list below the graph should remain the same. If possible, it would be good to build some interaction i.e. either to click on an edge and highlight something in the table or the other way around, but this is not a must.
3. The highlight doesn't work for me, and it's also not a must, but I believe the edge highlight feature is already present in the 3D viewer.
4. A "none" value is missing for the compartment highlight - the selector appears just disabled, which is confusing ([example](https://metabolicatlas.org/explore/Human-GEM/interaction-partners/MAM01903r).
5. When left-click, one is supposed to see a small card to the right. For now, that card contains only 2 buttons: GB and IP.
6. When right-clicking, the only option should be to expand the network. To load the Interaction Partners of the intended component, there is already a button on the side of the page.
7. For now, there will be no search.
8. It is envisio ed that the nodes are not customizable in any way (shape, color).
9. There is to requirement to _toggle_ the labels, the default is to see them.
10. Answered in (1).
11. There is no requirement about toggleing the background color. My recommendation though would be to keep things consistent with the 3D viewer.

**Comment by inghylt** [comment] 2022-09-20 13:52
Summary whether listed points should be doable or not (+ some additional questions)
### From [comment above](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/1130#issuecomment-1250975958)
#### 1. In interaction partners, the nodes are only genes and metabolites. As a long-term version, one should design the system with the possibility to also have just genes or just metabolites. This is, however, beyond the scope here.

Yes, since we have
```
MetabolicAtlas/api/src/neo4j/queries/3d-network.js

nodes: apoc.coll.flatten(COLLECT(value.data.nodes)),
links: apoc.coll.flatten(COLLECT(value.data.links))
```

and

```
MetabolicAtlas/frontend/src/components/explorer/mapViewer/ThreeDviewer.vue

const graphData = customizedNetwork || this.network;
const nodeTypes = new Set(graphData.nodes.map(n => n.g));
const nodeTextures = NODE_TEXTURES.filter(t => nodeTypes.has(t.group));
```

this should be general enough for us to only work with genes and/or metabolites

#### 2. The reaction list below the graph should remain the same. If possible, it would be good to build some interaction i.e. either to click on an edge and highlight something in the table or the other way around, but this is not a must.

Yes, since the edges are blue, red or yellow depending on default, hover or click
```
3d-network-viewer/src/met-atlas-viewer.js

function setConnectionsColor(spriteNum, color = undefined) {
let node = nodeInfo[spriteNum];
    if (!node) return;

    node.connections.from.forEach(conn => {
    ...
    }
    node.connections.to.forEach(conn => {
    ...
    }
```

We already have the reaction table functionality from IP in `MetabolicAtlas/frontend/src/components/explorer/interactionPartners/CytoscapeTable.vue`, we should be able to reuse that table. We should also be able to find the relevant node id:s to pass into `setConnectionsColor` since we have mapping between node and reaction id today in `MetabolicAtlas/frontend/src/components/explorer/InteractionPartners.vue`

```
<div v-show="clickedElm">
              <span class="button is-dark">Highlight reaction:</span>
            </div>
            <div>
              <template v-if="clickedElm && clickedElm['reaction']">
                <template v-for="(r, index) in Array.from(clickedElm.reaction).slice(0, 16)">
```

#### 3. The highlight doesn't work for me, and it's also not a must, but I believe the edge highlight feature is already present in the 3D viewer.

Yes, since
```
3d-network-viewer/src/met-atlas-viewer.js

function setConnectionsColor(spriteNum, color = undefined) {
...
}
```

#### 4. A "none" value is missing for the compartment highlight - the selector appears just disabled, which is confusing ([example](https://metabolicatlas.org/explore/Human-GEM/interaction-partners/MAM01903r).

Yes, highlight of Compartment or Subsystems should be doable since

```
3d-network-viewer/src/met-atlas-viewer.js

function setSpriteColor(spriteNum, color = undefined) {
...
}
```
and we should be able to use the data available in IP, example below

```
MetabolicAtlas/frontend/src/components/explorer/InteractionPartners.vue

<select v-model="subsystemHL" @change.prevent="highlightSubsystem">
                          <option value="" disabled>Select a subsystem</option>
                          <option v-for="sub in subsystemList" :key="sub" :value="sub">
```
#### 5. When left-click, one is supposed to see a small card to the right. For now, that card contains only 2 buttons: GB and IP.

Yes, since

```
MetabolicAtlas/frontend/src/components/explorer/mapViewer/ThreeDviewer.vue

this.controller = MetAtlasViewer('viewer3d');
this.controller.setNodeSelectCallback(this.selectElement);

...

async selectElement(element) {
...
this.$emit('updatePanelSelectionData', selectionData);
...
}
```

Then we should just create a selectElement(element) relevant to IP, where we do an this.$emit() to panel relevant to IP with relevant data to create GB and IP buttons

Not 100% how we would go about separating left and right click, but might be possible to rewrite current onMouseClick in `3d-network-viewer/src/met-atlas-viewer.js` to:

```
function onMouseClick(event) {

    var items = pickInScene(event);

    if (items.length > 0) {
      select(items);
      // check if left and right click callback methods are set
      if (leftClickSelectCallback && rightClickSelectCallback) {
          // do something depending on if mouseClick was left or right
      } else if (nodeSelectCallback && items.length === 1) {
        nodeSelectCallback(nodeInfo[items[0]]);
      }
    ...
  }
  ```

#### 6. When right-clicking, the only option should be to expand the network. To load the Interaction Partners of the intended component, there is already a button on the side of the page.

Yes, since we should be able to making another query similar to

```
MetabolicAtlas/api/src/neo4j/queries/3d-network.js

nodes: apoc.coll.flatten(COLLECT(value.data.nodes)),
links: apoc.coll.flatten(COLLECT(value.data.links))
```
and merging that result with the already existing { nodes:, links: } network

~7. For now, there will be no search.~
~8. It is envisio ed that the nodes are not customizable in any way (shape, color).~
#### 9. There is to requirement to _toggle_ the labels, the default is to see them.

Yes, since
```
3d-network-viewer/src/met-atlas-viewer.js
  
function toggleLabels() {
```

~10. Answered in (1).~
#### 11. There is no requirement about toggleing the background color. My recommendation though would be to keep things consistent with the 3D viewer.

Yes, since

```
3d-network-viewer/src/met-atlas-viewer.js

function setBackgroundColor(color) {
    scene.background = new Color(color);
  }
```

### Additional questions
#### 13. Reproducible URL:
@mihai-sysbio We guess that IP and applied data overlay should be reproducible by copying the url?

We think this should be doable since we have `queryParams` in `MetabolicAtlas/frontend/src/store/modules/dataOverlay.js` and `MetabolicAtlas/frontend/src/store/modules/maps.js`  and we should be able to reuse or draw inspiration from these. Overlay might be a bit messy since that store is shared between 2D map, 3D map and IP

#### 14. Export to PNGhML or GraphML
@mihai-sysbio This functionality exist in current IP. We guess this is not needed if we make a reproducible URL, correct?

#### 15. Move from 3D to 2D
@MalinAhlberg had some memory of this being mentioned. @mihai-sysbio should the IP be in 2D all the time? This might be doable by using `3d-network-viewer/src/met-atlas-viewer.js` but with z pos value as 0. Or should IP users have an option to switch between 2D and 3D? Or 3D all the time?

**Comment by e0** [comment] 2022-09-20 21:20
This looks like a really thorough pre-study! It's nice to see that it looks like the `3d-network-viewer` could be used without too much modification, which would be great. Was there any research into using any other libraries such as [d3-force](https://observablehq.com/collection/@d3/d3-force) in case the `3d-network-viewer` doesn't pan out? I'm just curious and it's fine if we haven't done this and don't plan to atm, especially if there is high confidence that the `3d-network-viewer` should work.

---

> #### 2. The reaction list below the graph should remain the same. If possible, it would be good to build some interaction i.e. either to click on an edge and highlight something in the table or the other way around, but this is not a must.

Should it also be possible to shift click additional edges or table rows to highlight multiple ones? Maybe add this as a nice-to-have? I imagine we could use a list variable to be used as a single source of truth for both edges and tables are synced.

---

> #### 5. When left-click, one is supposed to see a small card to the right. For now, that card contains only 2 buttons: GB and IP.
> Not 100% how we would go about separating left and right click

Just want to add, it seems like this is how the right-click could be detected: https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event

---

> ### Additional questions
> #### 15. Move from 3D to 2D
> @MalinAhlberg had some memory of this being mentioned. @mihai-sysbio should the IP be in 2D all the time? This might be doable by using `3d-network-viewer/src/met-atlas-viewer.js` but with z pos value as 0. Or should IP users have an option to switch between 2D and 3D? Or 3D all the time?

Just want to mention here that the [graph layout library](https://github.com/anvaka/ngraph.forcelayout) that we use has support for both 2D and 3D (and apparently even higher dimensions!). So as a starting point we could just try to use `const layout = createLayout(g, { dimensions: 2 });` and see how the `3d-network-viewer` handles that without manually setting the `z` value.

**Comment by inghylt** [comment] 2022-09-21 07:46
Below are some examples from when using `const layout = createLayout(g, { dimensions: 2 });` in `MetabolicAtlasapi/src/utils/3d-network.js`. This is an encouraging result IMO!

http://localhost/explore/Human-GEM/map-viewer/fatty_acid_elongation_odd_chain?dim=3d&panel=0&sel=MAM02759r&search=&coords=-291.62,-304.49,0.71,-57.1,26.6,280.6&dataTypes=None&dataSources=None&dataSets=None
![image](https://user-images.githubusercontent.com/32480198/191445336-d5bfaa98-b225-440c-b70e-f46401d8ea7a.png)

http://localhost/explore/Human-GEM/map-viewer/acyl_coa_hydrolysis?dim=3d&panel=0&sel=MAM02759r&search=&coords=-291.62,-304.49,0.71,-4.53,2.03,300.82&dataTypes=None&dataSources=None&dataSets=None
![image](https://user-images.githubusercontent.com/32480198/191444453-85997f55-da08-46fe-a691-f1bc744bed02.png)

http://localhost/explore/Human-GEM/map-viewer/acylglycerides_metabolism?dim=3d&panel=0&sel=MAM02759r&search=&coords=-291.62,-304.49,0.71,-56.94,48.34,291.44&dataTypes=None&dataSources=None&dataSets=None
![image](https://user-images.githubusercontent.com/32480198/191444630-b2e38bf0-e4b8-41e6-b3c6-484582468d0d.png)

**Comment by e0** [comment] 2022-09-21 07:50
That looks really good @inghylt! I played with this a bit too and I guess the changes we would want to make are with the mouse controls, for example mouse dragging should pan instead of rotating and zoom should be disabled.

Btw, if things work out, I assume we would like to rename the `3d-network-viewer` (repo and package names) right? Maybe to just `network-viewer`?
cc @mihai-sysbio

**Comment by nanjiangshu** [comment] 2022-09-21 08:48
Thanks @inghylt for a great summary and comprehensive research of the possibility to redo **IP** with 3D map viewer. Based on these findings, I think we should be able to go ahead with the **IP** redo and refactoring. 
As to the Export function
> 14. Export to PNGhML or GraphML

I think it is good to keep it even when the URL is reproducible. It's more convenient to share or use the image in documents than the URL.

**Comment by mihai-sysbio** [comment] 2022-09-21 09:12
This has been a great discussion, so nice!

> 13. Reproducible URL:

Yes, the same rationale for it as for the Map Viewer.

> 14. Export to PNGhML or GraphML

This is needed for users to use the graph in other visualisation tools, so this feature needs to still exist.

> 15. Move from 3D to 2D

For now, restricting the z to `0` makes a lot of sense. A proper switch between 2D and 3D should also change the styling (like the 2D maps), so that is out of scope. And it's reported as separate issue(s).

> Should it also be possible to shift click additional edges or table rows to highlight multiple ones? Maybe add this as a nice-to-have? I imagine we could use a list variable to be used as a single source of truth for both edges and tables are synced.

This has been reported as https://github.com/MetabolicAtlas/private-issues/issues/78, so for now it's out of scope.

**Comment by inghylt** [comment] 2022-09-21 09:25
Based on the comments above, the foreseen upcoming work is then to:
- [ ] Create {nodes: [], links: []} object for IP genes and metabolites data
- [ ] Generate 2D graph based on this object
- [ ] When (left) clicking, show GB and IP. Possibly also an "Expand network" button instead of having that as right click option
- [ ] Add expand network functionality (right click or through button next to GB and IP)
- [ ] Add overlay functionality
- [ ] Make sure URL params are updated according to graph and overlay
- [ ] Add visualization of reactions in reactions table
- [ ] Add visualization of Compartment/Subsystem
- [ ] Add functionality to export to PNGhML or GraphML
- [ ] Update mouse controls
- [ ] Add button to toggle labels (probably makes sense to more or less copy MapControls.vue)
- [ ] Nice to have but not required in first iteration: Button to show only genes or metabolites
- [ ] Nice to have but not required in first iteration: Button to switch between 2D and 3D
- [ ] Nice to have but not required in first iteration: Shift click additional edges or table rows to highlight multiple reactions

**Comment by inghylt** [comment] 2022-09-22 07:45
Closing this to make actual implementation in #1144

**Closed by inghylt** 2022-09-22 07:45 UTC
Labels: good for pair programming, research

**Comment by inghylt** [comment] 2022-09-22 07:48
Changed the time estimation to 3
