### ISSUE TITLE
use compression for api requests

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#1093] opened 2022-08-15 12:39 UTC
**Please describe the feature**

As a user interested in reaction data, I want the reaction data to load fast so that I don't have to wait for it to download.

This can be more generically expanded to all API queries.

**Acceptance Criteria**

- [ ] requests to the API are compressed with a fairly popular algorithm supported by most browsers
- [ ] The changes do not reduce the performance

**Additional context**

Some of the responses/data returned by the `api` is not compressed, which means it takes longer time to transfer.
Compression should be enabled either in the `api` container or directly in the `nginx` container.

**Comment by MalinAhlberg** [comment] 2022-09-26 07:54
Solve at nginx level if possible

**Comment by e0** [comment] 2022-10-04 17:56
From what I can see the compression is working just fine. If you know of any specific results that is not being compressed please let me know. Otherwise I think this issue can be closed. Also wondering, how was this originally tested?

Following is a couple of comparisons of uncompressed requests vs. compressed ones using a header that most browsers would send.

```bash
$ curl https://metabolicatlas.org/api/v2/repository/integrated_models/ --silent --write-out "%{size_download}\n" --output /dev/null
7864 -> size of integrated models uncompressed

$ curl https://metabolicatlas.org/api/v2/repository/integrated_models/ --silent -H "Accept-Encoding: gzip,deflate,br" --write-out "%{size_download}\n" --output /dev/null
1321 -> size of integrated models compressed

$curl https://metabolicatlas.org/api/v2/reactions/MAR05293?model=HumanGem&version=1_10_0 --silent --write-out "%{size_download}\n" --output /dev/null
1914 -> size of reaction data uncompressed

$ curl https://metabolicatlas.org/api/v2/reactions/MAR05293?model=HumanGem&version=1_10_0 --silent -H "Accept-Encoding: gzip,deflate,br" --write-out "%{size_download}\n" --output /dev/null
669 -> size of reaction data compressed
```

**Comment by mihai-sysbio** [comment] 2022-10-05 10:04
Here is an example of an API request that is not compressed:

<img width="774" alt="image" src="https://user-images.githubusercontent.com/23480589/194035109-1897c26e-a103-4661-94e8-2b67b24121bd.png">

As indicated in the issue, this is even a bigger problem for the reaction data overlay (fluxomics). So at least this part of the API should be compressed to resolve this issue. My recommendation, though, would be to review all API routes.

**Comment by e0** [comment] 2022-10-05 11:22
Since [this commit](https://github.com/MetabolicAtlas/MetabolicAtlas/commit/872b763ed012d6f0cbf6236b522a6e6b86ecfc5d#diff-bb22e7e0b75f781c46992a3ece08b5526fcea81fe7629d3d44831752229c5293), TSV files are no longer being served from this endpoint so this specific case (data overlay TSV files) is no longer an issue.

In the current state of the production server, it also seems capable of sending compressed TSV files as long as the correct headers are provided. One could configure the `axios` headers to explicitly set the `Accept-Encoding` if necessary. This is something to be done on the frontend though and it seems like no server side changes are needed.

```bash
$ curl https://metabolicatlas.org/api/v2/data-overlay/Human-GEM/transcriptomics/hpaRna.tsv --silent --write-out "%{size_download}\n" --output /dev/null
918987 -> size uncompressed with no headers

$ curl https://metabolicatlas.org/api/v2/data-overlay/Human-GEM/transcriptomics/hpaRna.tsv --silent -H "Accept-Encoding: gzip,deflate,br" --write-out "%{size_download}\n" --output /dev/null
918987 -> size uncompressed with "Accept-Encoding: gzip,deflate,br"

$ curl https://metabolicatlas.org/api/v2/data-overlay/Human-GEM/transcriptomics/hpaRna.tsv --silent -H "Accept-Encoding: gzip,deflate" --write-out "%{size_download}\n" --output /dev/null
238191 -> size compressed with "Accept-Encoding: gzip,deflate"
```

**Comment by nanjiangshu** [comment] 2022-10-06 12:46
I agree with @e0 that the compression (with gzip) is enabled at the API. Maybe we can modify this issue to configure the proper header at the frontend?

**Comment by e0** [comment] 2022-10-06 12:51
@nanjiangshu I should have made this clearer. It seems like the headers (`gzip,deflate,b`) that are sent by default from the browsers work just fine for `json` responses. In other words, users of the website should be getting compressed responses automatically. The problem [mentioned here](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/1093#issuecomment-1268221477) is just about the TSV files which are no longer being served. So I don't think any changes in the frontend are needed.

**Comment by inghylt** [comment] 2022-10-06 14:19
Trying to summarize the discussion above
- Compression is already enabled in the API
- The problem seem to occur when whole tsv files are returned as response to a query
- With the current state of main that will be deployed asap, we don't have any responses that return whole tsv files. I have verified this myself

So, seems to me like we can close this issue. But probably makes sense to get input from other people as well

**Comment by nanjiangshu** [comment] 2022-10-07 06:59
> @nanjiangshu I should have made this clearer. It seems like the headers (`gzip,deflate,b`) that are sent by default from the browsers work just fine for `json` responses. In other words, users of the website should be getting compressed responses automatically. The problem [mentioned here](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/1093#issuecomment-1268221477) is just about the TSV files which are no longer being served. So I don't think any changes in the frontend are needed.

Hi @e0, thanks for the clarification. But I still have one question, since the header `gzip,deflate` or just `gzip` will compress all API requests, including the full `tsv` files, why is `br` added?

**Comment by e0** [comment] 2022-10-07 10:33
> Hi @e0, thanks for the clarification. But I still have one question, since the header `gzip,deflate` or just `gzip` will compress all API requests, including the full `tsv` files, why is `br` added?

That's a good question. It seems that this `gzip,deflate,br` is what the browsers (I tested with Safari and Firefox) are sending by default, so `br` is not something that we have manually added. I'm not too familiar with this topic. If you would like to read more about it I suggest you can start [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation).

<img width="791" alt="image" src="https://user-images.githubusercontent.com/423498/194533418-c0ac971d-38ff-48f5-9cf7-28240e38b225.png">

**Comment by e0** [comment] 2022-10-07 10:44
It seems like enough people have confirmed this, either here or on slack so I think it can be closed for now. Please re-open if anything changes.

**Closed by e0** 2022-10-07 10:44 UTC
