### ISSUE TITLE
Timeline view for integrated GEMs

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/MetabolicAtlas#949] opened 2022-04-05 09:22 UTC
**Please describe the feature**

As a user, I want to visualize integrated GEMs in a timeline view so that I can understand their history of development.

**Acceptance Criteria**

- [ ] The documentation is updated accordingly (on the webpage)
- [ ] The changes are tested on multiple models and browsers
- [ ] The API response is the same as before
- [ ] The changes do not affect the deployment
- [ ] The changes do not reduce the performance (e.g. by adding a large library)
- [ ] The timeline is visually appealing and interactive (at least clicking on nodes for more details) based on the design from #929

**Additional context**

- If the related data collection issue is not completed at the start of the issue, use mock data.
- If the related data collection issue is not completed when a PR for this issue is ready to be made, please set the PR to draft mode.

**Comment by inghylt** [comment] 2022-04-06 12:05
https://js.cytoscape.org/

Could be a beneficial lib

**Comment by e0** [comment] 2022-04-11 08:58
We haven't decided on the data format yet but I feel like we can start to research libraries and perhaps some other frontend integration related things so I'm starting to work on this now.

**Comment by e0** [comment] 2022-04-11 13:49
I have been searching for good alternatives that we can potentially use but it seems difficult to find good open-source options for this type of charts. The best one I found is this one using cytoscape: https://cytoscape.org/cytoscape.js-klay/

@mihai-sysbio I see that the `cytoscape.cjs.js` takes up a big chunk of the dependencies chart. Do we have any metrics on the performance in production? Also do you have any recommendations on possible replacements?

For this specific issue, I think it is possible to make something from scratch. I'm more curious about potential replacements for interaction partners. I think it would be much more challenging to make that from scratch and if we do realize that we need to keep `cytoscape`, it should also speed up the development of this issue by a lot if we can use it here. Or perhaps there is already a good potential alternative for interaction partners, in which case we could consider using it here.

**Comment by mihai-sysbio** [comment] 2022-04-11 15:08
> I have been searching for good alternatives that we can potentially use but it seems difficult to find good open-source options for this type of charts. The best one I found is this one using cytoscape: https://cytoscape.org/cytoscape.js-klay/

Cool, it would be nice to list what things you have looked at (so that others won't look at the same thing). For example, you probably have dismissed something like [jQuery.Timeline](https://github.com/ka215/jquery.timeline) for the reason that it depends on jQuery, [Vega-Light](https://vega.github.io/vega-lite/examples/), or [this](https://observablehq.com/@austil/js-frameworks-timeline-trends).

> @mihai-sysbio I see that the `cytoscape.cjs.js` takes up a big chunk of the dependencies chart. Do we have any metrics on the performance in production?

I'm not entirely sure what performance metrics you're interested in. The obvious to me would be to look at the total size of JS transferred to the client that even compressed is too large (~430kb of libraries, and another ~100kb for the app, making up for >1.5mb uncompressed).

>  Also do you have any recommendations on possible replacements? 
For this specific issue, I think it is possible to make something from scratch. I'm more curious about potential replacements for interaction partners. I think it would be much more challenging to make that from scratch and if we do realize that we need to keep `cytoscape`, it should also speed up the development of this issue by a lot if we can use it here. Or perhaps there is already a good potential alternative for interaction partners, in which case we could consider using it here.

Cytoscape is used only for the _Interaction Partners_ feature, and we already have the 3D viewer performing largely equivalent functionality, so I think that would be the best replacement. Moreover, the Cytoscape-powered 3D viewer is very limited in terms of performance (amount of nodes it can handle).

If we would want to, we could probably also use the 3D viewer for the timeline as well, since it's so much like the `cytoscape.js-klay` example mentioned above.

**Comment by e0** [comment] 2022-04-11 15:46
> > I have been searching for good alternatives that we can potentially use but it seems difficult to find good open-source options for this type of charts. The best one I found is this one using cytoscape: https://cytoscape.org/cytoscape.js-klay/
> 
> Cool, it would be nice to list what things you have looked at (so that others won't look at the same thing). For example, you probably have dismissed something like [jQuery.Timeline](https://github.com/ka215/jquery.timeline) for the reason that it depends on jQuery, [Vega-Light](https://vega.github.io/vega-lite/examples/), or [this](https://observablehq.com/@austil/js-frameworks-timeline-trends).

Thanks. I haven't seen any of these examples. Vega Lite looks a bit interesting but I don't see anything too similar to what we want. The jQuery one looks better than any other ones I looked at. I looked at some general charting libraries as well as more specific ones from a couple of sites like https://bashooka.com/coding/javascript-timeline-libraries/ and https://www.webtopic.com/javascript-timeline-libraries/. Also searched on GitHub directly a bit. It was probably a few dozen libraries in total and I didn't find any worthy of mentioning for various factors (not open source, unmaintained, lacking features etc.).

> > @mihai-sysbio I see that the `cytoscape.cjs.js` takes up a big chunk of the dependencies chart. Do we have any metrics on the performance in production?
> 
> I'm not entirely sure what performance metrics you're interested in. The obvious to me would be to look at the total size of JS transferred to the client that even compressed is too large (~430kb of libraries, and another ~100kb for the app, making up for >1.5mb uncompressed).

I'm interested to know how the size impacts our users. I get that the bundle size is larger than recommended but if it's fast enough for our users, how big of a problem is it? For example, to render the 3D network, using any kind of library would require a lot of resources simply due to the number of items being drawn. If we were to reduce the size of our bundle, what kind of improvements would that mean for the user in relation to the features that we offer? How do the potential improvements compare to the development time needed? These are they type of questions I have in mind when asking about the performance metrics.

> > Also do you have any recommendations on possible replacements?
> > For this specific issue, I think it is possible to make something from scratch. I'm more curious about potential replacements for interaction partners. I think it would be much more challenging to make that from scratch and if we do realize that we need to keep `cytoscape`, it should also speed up the development of this issue by a lot if we can use it here. Or perhaps there is already a good potential alternative for interaction partners, in which case we could consider using it here.
> 
> Cytoscape is used only for the _Interaction Partners_ feature, and we already have the 3D viewer performing largely equivalent functionality, so I think that would be the best replacement. Moreover, the Cytoscape-powered 3D viewer is very limited in terms of performance (amount of nodes it can handle).
> 
> If we would want to, we could probably also use the 3D viewer for the timeline as well, since it's so much like the `cytoscape.js-klay` example mentioned above.

That's a good suggestion I think. Maybe not the 3D viewer repo but `three.js` could be a lower level option. I was also thinking of using `d3js` or interacting with the HTML `canvas` or `svg` elements directly.

**Comment by e0** [comment] 2022-04-19 16:17
I have been taking a look at `d3` today to evaluate its fit for this issue. `d3` is a low-level data viz framework and provides a developer friendly API that enables creation of visualizations with relatively little code. I found [this example](https://observablehq.com/@nitaku/tangled-tree-visualization-ii), which looks somewhat close to what we would like to achieve. Since [version 4](https://github.com/d3/d3/blob/main/CHANGES.md#changes-in-d3-40), `d3` has been divided into many small libraries, which lets us import less code and should also work well with tree-shaking.

Based on the session today, I feel optimistic about the capability and developer experience of `d3`. I have add [a commit](https://github.com/MetabolicAtlas/MetabolicAtlas/commit/a3220c679d89b5a8a408040ba6d869bb72c52ff6) to try it out in our project, which is adapted from [this example](https://bl.ocks.org/denjn5/4bdda16ab6338772a7882ec2f5f2a9c7).

If we would like to continue using `d3`, the work should continue with breaking down the requirements and building the individual functions we need to create the chart. Even though it seems developer friendly and well made, it could still take a relatively long time to complete this issue since it requires us to "hand craft" many new components.

Another area that I would like to understand more is how, or if, tree-shaking is currently done in the project. For example, if we could analyze the production bundle with the one shown in http://localhost:81, is there any difference between the packages? As for the development bundle size of `d3`, I compared (see screenshots below) importing `d3` vs. only the modules (`d3-selection d3-hierarchy d3-shape`) that are used. While there was a big difference, the local bundle size is still quite large (682.85KB), which is comparable to `cytoscape` (746.57KB). If `cytoscape` is already marked for removal and bundle size is indeed a problem, maybe we should think more about using `d3` if we can't bring down the size for production environments.

It would be nice if we could discuss more about this at the stand-up tomorrow if there is time.

<img src="https://user-images.githubusercontent.com/423498/164048945-f210fce1-a6aa-4f34-a278-125fbd2c3284.png" width=300 />
<img src="https://user-images.githubusercontent.com/423498/164048975-60245e5b-a290-4326-a4d5-7fb4ef2b234f.png" width=300 />

**Comment by mihai-sysbio** [comment] 2022-04-21 04:45
The bundle size can differ a lot, see this [d3 example on bundlephobia](https://bundlephobia.com/package/d3@7.4.4). The webpack analyzer used at port 81 is enabled only for `development`, so one idea might be to enable it for `production` and deploy to `dev` for real-world stats: https://github.com/MetabolicAtlas/MetabolicAtlas/blob/develop/frontend/vue.config.js#L19-L25

**Comment by mihai-sysbio** [comment] 2022-04-21 04:47
> I found [this example](https://observablehq.com/@nitaku/tangled-tree-visualization-ii), which looks somewhat close to what we would like to achieve.

Very nice example! Here are some others from the paid library [yFiles](https://live.yworks.com/demos/) for more inspiration.

**Comment by nanjiangshu** [comment] 2022-04-21 13:18
Thanks for the in-depth research @e0 and @mihai-sysbio made. The example Shan provided with `d3` looks really nice. Regarding the performance issue with `cytospace`, I'm wondering if this is mainly caused by the size of the bundle or something else? If just looking at the bundle size, `cytospace` is large but far away from the biggest.

**Comment by inghylt** [comment] 2022-04-22 07:50
Really nice work so far!

`d3` seems like a legit option. I'm just curious about the concerns regarding performance of `cytospace`. Do users really experience bundle size as a problem? And I don't think we will have a massive amount of nodes since there are not that many releases. Maybe that will change when we incorporate [B) and D)](https://app.zenhub.com/workspaces/metatlas-sprint-607745622d49260019ce115a/issues/metabolicatlas/private-issues/127) data, but on the other hand I don't think we will render all of the nodes of A) B) and D) in the same section?

**Comment by mihai-sysbio** [comment] 2022-04-22 10:05
> Do users really experience bundle size as a problem?

While historically we have improved the bundle size, it is still a problem reported by several website performance analyses https://pagespeed.web.dev/report?url=https%3A%2F%2Fmetabolicatlas.org%2F&form_factor=desktop

**Comment by e0** [comment] 2022-04-26 13:58
Here is a little WIP update for how the timeline chart looks like using mock data. Still got the interactions (dropdown) and refactoring on my todo list among some other minor things.

While working on this, I realized that `d3` is capable of outputting everything into an `svg`, which means that it should be possible for us to not include `d3` in the production bundle at all. I think we could, and probably should, create a new repo that's only responsible for generating the `svg`. We can then add this to our pipeline similarly to how we currently use https://github.com/MetabolicAtlas/data-generation.

<svg width="1200" height="350"><g transform="translate(0, 350)" fill="none" font-size="10" font-family="sans-serif" text-anchor="middle"><path class="domain" stroke="currentColor" d="M0,-6V0H1100V-6"></path><g class="tick" opacity="1" transform="translate(17.82630520910899,0)"><line stroke="currentColor" y2="-6"></line><text fill="currentColor" y="-9" dy="0em">2019</text></g><g class="tick" opacity="1" transform="translate(98.17493348983197,0)"><line stroke="currentColor" y2="-6"></line><text fill="currentColor" y="-9" dy="0em">April</text></g><g class="tick" opacity="1" transform="translate(179.45395348293016,0)"><line stroke="currentColor" y2="-6"></line><text fill="currentColor" y="-9" dy="0em">July</text></g><g class="tick" opacity="1" transform="translate(261.62614951990855,0)"><line stroke="currentColor" y2="-6"></line><text fill="currentColor" y="-9" dy="0em">October</text></g><g class="tick" opacity="1" transform="translate(343.835561225382,0)"><line stroke="currentColor" y2="-6"></line><text fill="currentColor" y="-9" dy="0em">2020</text></g><g class="tick" opacity="1" transform="translate(425.07736554998513,0)"><line stroke="currentColor" y2="-6"></line><text fill="currentColor" y="-9" dy="0em">April</text></g><g class="tick" opacity="1" transform="translate(506.3563855430833,0)"><line stroke="currentColor" y2="-6"></line><text fill="currentColor" y="-9" dy="0em">July</text></g><g class="tick" opacity="1" transform="translate(588.5285815800618,0)"><line stroke="currentColor" y2="-6"></line><text fill="currentColor" y="-9" dy="0em">October</text></g><g class="tick" opacity="1" transform="translate(670.737993285535,0)"><line stroke="currentColor" y2="-6"></line><text fill="currentColor" y="-9" dy="0em">2021</text></g><g class="tick" opacity="1" transform="translate(751.0866215662581,0)"><line stroke="currentColor" y2="-6"></line><text fill="currentColor" y="-9" dy="0em">April</text></g><g class="tick" opacity="1" transform="translate(832.3656415593563,0)"><line stroke="currentColor" y2="-6"></line><text fill="currentColor" y="-9" dy="0em">July</text></g><g class="tick" opacity="1" transform="translate(914.5378375963346,0)"><line stroke="currentColor" y2="-6"></line><text fill="currentColor" y="-9" dy="0em">October</text></g><g class="tick" opacity="1" transform="translate(996.747249301808,0)"><line stroke="currentColor" y2="-6"></line><text fill="currentColor" y="-9" dy="0em">2022</text></g><g class="tick" opacity="1" transform="translate(1077.095877582531,0)"><line stroke="currentColor" y2="-6"></line><text fill="currentColor" y="-9" dy="0em">April</text></g></g><g fill="none" font-size="10" font-family="sans-serif" text-anchor="start"><path class="domain" stroke="currentColor" d="M6,350H0V0H6"></path><g class="tick" opacity="1" transform="translate(0,200)"><line stroke="currentColor" x2="6"></line><text fill="currentColor" x="9" dy="0.32em">Yeast</text></g><g class="tick" opacity="1" transform="translate(0,150)"><line stroke="currentColor" x2="6"></line><text fill="currentColor" x="9" dy="0.32em">Rat</text></g><g class="tick" opacity="1" transform="translate(0,100)"><line stroke="currentColor" x2="6"></line><text fill="currentColor" x="9" dy="0.32em">Mouse</text></g><g class="tick" opacity="1" transform="translate(0,50.000000000000014)"><line stroke="currentColor" x2="6"></line><text fill="currentColor" x="9" dy="0.32em">Human</text></g></g><path d="M453.73343029114153,50C456.323640818394,65.83333333333334,458.9138513456466,81.66666666666667,484.8159566181725,90C510.7180618906984,98.33333333333333,559.9320619084973,99.16666666666666,609.1460619262963,100" stroke="lightgray" fill="none"></path><path d="M453.73343029114153,50C456.323640818394,81.66666666666667,458.9138513456466,113.33333333333334,484.8159566181725,130C510.7180618906984,146.66666666666666,559.9320619084973,148.33333333333331,609.1460619262963,150" stroke="lightgray" fill="none"></path><g><line x1="80.38584394921799" y1="50" x2="134.86958262591017" y2="50" style="stroke: lightgray;"></line><line x1="134.86958262591017" y1="50" x2="162.55803998619638" y2="50" style="stroke: lightgray;"></line><line x1="162.55803998619638" y1="50" x2="244.73023602317477" y2="50" style="stroke: lightgray;"></line><line x1="244.73023602317477" y1="50" x2="416.2200364481731" y2="50" style="stroke: lightgray;"></line><line x1="416.2200364481731" y1="50" x2="453.73343029114153" y2="50" style="stroke: lightgray;"></line><line x1="453.73343029114153" y1="50" x2="699.3568423581966" y2="50" style="stroke: lightgray;"></line><line x1="699.3568423581966" y1="50" x2="900.3214522312416" y2="50" style="stroke: lightgray;"></line></g><g><circle r="10" cy="50" cx="80.38584394921799"></circle><circle r="5" cy="50" cx="134.86958262591017"></circle><circle r="5" cy="50" cx="162.55803998619638"></circle><circle r="5" cy="50" cx="244.73023602317477"></circle><circle r="5" cy="50" cx="416.2200364481731"></circle><circle r="5" cy="50" cx="453.73343029114153"></circle><circle r="5" cy="50" cx="699.3568423581966"></circle><circle r="5" cy="50" cx="900.3214522312416"></circle></g><g><text y="70" x="80.38584394921799" transform="translate(-10, 0)" style="font-size: 10px;">1.0.0</text><text y="70" x="134.86958262591017" transform="translate(-10, 0)" style="font-size: 10px;">1.1.0</text><text y="70" x="162.55803998619638" transform="translate(-10, 0)" style="font-size: 10px;">1.2.0</text><text y="70" x="244.73023602317477" transform="translate(-10, 0)" style="font-size: 10px;">1.3.0</text><text y="70" x="416.2200364481731" transform="translate(-10, 0)" style="font-size: 10px;">1.4.0</text><text y="70" x="453.73343029114153" transform="translate(-10, 0)" style="font-size: 10px;">1.5.0</text><text y="70" x="699.3568423581966" transform="translate(-10, 0)" style="font-size: 10px;">1.6.0</text><text y="70" x="900.3214522312416" transform="translate(-10, 0)" style="font-size: 10px;">1.7.0</text></g><g><line x1="609.1460619262963" y1="100" x2="683.2796735683529" y2="100" style="stroke: lightgray;"></line></g><g><circle r="10" cy="100" cx="609.1460619262963"></circle><circle r="5" cy="100" cx="683.2796735683529"></circle></g><g><text y="120" x="609.1460619262963" transform="translate(-10, 0)" style="font-size: 10px;">1.0.0</text><text y="120" x="683.2796735683529" transform="translate(-10, 0)" style="font-size: 10px;">1.1.0</text></g><g><line x1="609.1460619262963" y1="150" x2="683.2796735683529" y2="150" style="stroke: lightgray;"></line></g><g><circle r="10" cy="150" cx="609.1460619262963"></circle><circle r="5" cy="150" cx="683.2796735683529"></circle></g><g><text y="170" x="609.1460619262963" transform="translate(-10, 0)" style="font-size: 10px;">1.0.0</text><text y="170" x="683.2796735683529" transform="translate(-10, 0)" style="font-size: 10px;">1.1.0</text></g><g><line x1="128.61735031874878" y1="200" x2="217.04177866288856" y2="200" style="stroke: lightgray;"></line><line x1="217.04177866288856" y1="200" x2="299.213974699867" y2="200" style="stroke: lightgray;"></line><line x1="299.213974699867" y1="200" x2="389.42475513176714" y2="200" style="stroke: lightgray;"></line><line x1="389.42475513176714" y1="200" x2="516.2557533627555" y2="200" style="stroke: lightgray;"></line><line x1="516.2557533627555" y1="200" x2="861.9148823443929" y2="200" style="stroke: lightgray;"></line></g><g><circle r="10" cy="200" cx="128.61735031874878"></circle><circle r="5" cy="200" cx="217.04177866288856"></circle><circle r="5" cy="200" cx="299.213974699867"></circle><circle r="5" cy="200" cx="389.42475513176714"></circle><circle r="5" cy="200" cx="516.2557533627555"></circle><circle r="5" cy="200" cx="861.9148823443929"></circle></g><g><text y="220" x="128.61735031874878" transform="translate(-10, 0)" style="font-size: 10px;">1.0.0</text><text y="220" x="217.04177866288856" transform="translate(-10, 0)" style="font-size: 10px;">1.1.0</text><text y="220" x="299.213974699867" transform="translate(-10, 0)" style="font-size: 10px;">1.2.0</text><text y="220" x="389.42475513176714" transform="translate(-10, 0)" style="font-size: 10px;">1.3.0</text><text y="220" x="516.2557533627555" transform="translate(-10, 0)" style="font-size: 10px;">1.4.0</text><text y="220" x="861.9148823443929" transform="translate(-10, 0)" style="font-size: 10px;">1.5.0</text></g></svg>

**Comment by mihai-sysbio** [comment] 2022-04-27 04:20
> While working on this, I realized that `d3` is capable of outputting everything into an `svg`, which means that it should be possible for us to not include `d3` in the production bundle at all.

Oh that would be sweet!

> create a new repo that's only responsible for generating the `svg`.

I guess there are multiple ways of doing this, perhaps also as part of the `data-generation` repository, since the source data will sit in `data-files`. Regardless, at some point I think we should re-discuss the monorepo concept again.

**Comment by e0** [comment] 2022-04-27 07:15
> I guess there are multiple ways of doing this, perhaps also as part of the `data-generation` repository, since the source data will sit in `data-files`. 

I like this suggestion!

**Comment by e0** [comment] 2022-04-27 13:23
Here comes another update with added interactivity. I left the styling very minimal as or now, please let me know if you have any preferences for colors or styles.

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/423498/165527658-dfaf39df-31ad-4f1f-ac75-8d4d9d487155.png">
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/423498/165527704-2242057a-2988-4883-b158-4119d364788d.png">

**Comment by nanjiangshu** [comment] 2022-04-29 12:28
Hi @e0, very nice illustration! It's great to know that d3 can generate the map as an SVG, with that performance will not be an issue. I agree with @mihai-sysbio that it is a good option to create this map in the data generation step but I'm open to other options. For the SVG map, one question is should we integrate the interactive module to the SVG map or implement the interactive module in the frontend, similar as the 2D Map viewer? 
Other comments for the styling of the map
1. color: I would prefer a lighter background color then the black 
2. I prefer a larger font size for the GEM name than the timeline 
3. When there are many row, it is not that easy to identify the GEM name of a far right node based on the Y ticks. I think it would be nice to show the GEM name in the pop up window when clicking a node
4. It might be a bit confusing to the user why the content of the pop up window is different when clicking different nodes. We probably need to explain it in an prominent place. Moreover, it should explain links to `GEM Browser` and `Map Viewer` are provided only for the latest versions

**Comment by e0** [comment] 2022-05-03 11:48
Here is another update after some refactoring and improvements. It's using the data @nanjiangshu compiled. This is excluding patch versions and the GEMs are sorted alphabetically from top to bottom. As you can see the distribution makes things look a bit weird, especially with the Yeast GEM having quite a few version prior to anything else.

Not quite sure how to go about solving this problem. If you have any ideas please let me know! In the mean time I will focus on the colors and design feedback from earlier.

<img width="1597" alt="image" src="https://user-images.githubusercontent.com/423498/166446687-33657180-8669-4b60-b606-2e66ba246b6f.png">

**Closed** 2022-05-06 13:02 UTC

**Comment by e0** [comment] 2022-05-06 13:06
The estimate for this was `5`, in retrospect it feels more like a `15`.
