### ISSUE TITLE
change IDs to links in enzyme table

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#1033] opened 2022-06-14 15:26 UTC
For all the elements that have dedicated pages with details, their IDs in the table should be links.

**Comment by e0** [comment] 2022-06-15 15:14
Consider merging this with #1032 since it would be a blocker and the scope of the issue is so tiny.

**Comment by e0** [comment] 2022-06-21 09:38
Closing since this is now included as an acceptance criteria in #1032.

**Closed by e0** 2022-06-21 09:38 UTC
